import React, { useEffect } from 'react';
import { ArrowRight, Check, ChevronRight, ClipboardCheck, Ruler, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { MetaTags } from '../components/ui/MetaTags';
import { Container } from '../components/layout/Container';
import { capabilitiesData } from '../data/capabilities';
import heroImage from '../assets/capabilities/capabilities-hero.png';
import turningImage from '../assets/capabilities/capability-cnc-turning.png';
import vmcImage from '../assets/capabilities/capability-vmc-milling.png';
import inspectionImage from '../assets/capabilities/capability-inspection.png';
import './CapabilitiesPage.css';
import './CapabilitiesPageOverrides.css';

const imageFor = (id: string) => capabilitiesData.find((item) => item.id === id)?.image || '';
const features: Record<string, string[]> = {
  turning: ['Precision shaft turning', 'Boring & internal profiling', 'Threading & grooving', 'Repeatable production'],
  milling: ['Profile milling', 'Precision pockets', 'Hole patterns', 'Face milling', 'Custom geometry'],
  fabrication: ['Custom fabrication', 'Cutting support', 'MIG welding', 'Engineering assemblies'],
  laser: ['Clean edge quality', 'Complex 2D profiles', 'Integrated support', 'Consistent geometry'],
  tooling: ['Custom tool holders', 'Application-led tooling', 'Precision die parts', 'Wear-conscious design'],
  fixtures: ['Part holding', 'Repeatable positioning', 'Inspection jigs', 'Production support'],
};
const sections = [
  { id: 'cnc-turning', label: 'CAPABILITY 01', title: 'Precision Turning for Complex Components.', text: 'CNC turning for cylindrical components manufactured to drawing-based dimensions, with repeatable production, engineered surfaces, and dependable support for custom component requirements.', image: turningImage, alt: 'CNC turning of a precision cylindrical metal component', set: 'turning', reverse: false },
  { id: 'vmc-milling', label: 'CAPABILITY 02', title: 'Complex Geometry. Controlled Machining.', text: 'VMC milling for profiles, pockets, hole patterns, face milling, and custom geometry. Our Jyoti CNC VMC 1260P with Siemens 828D supports controlled machining for demanding customer drawings.', image: vmcImage, alt: 'VMC milling a complex machined metal component', set: 'milling', reverse: true },
  { id: 'fabrication', label: 'CAPABILITY 04', title: 'Fabrication Supporting Industrial Requirements.', text: 'Custom fabrication support including cutting, welding, and engineering fabrication where required. MIG welding capability complements our machining and assembly workflow.', image: imageFor('fabrication'), alt: 'MIG welding and industrial fabrication support', set: 'fabrication', reverse: false },
  { id: 'laser-cutting', label: 'CAPABILITY 05', title: 'Clean Cutting. Consistent Geometry.', text: 'Laser cutting forms part of our integrated manufacturing support, helping prepare accurate profiles and clean geometries that move efficiently into downstream engineering work.', image: imageFor('laser-cutting'), alt: 'Precision laser cutting support for engineering components', set: 'laser', reverse: true },
  { id: 'tooling', label: 'CAPABILITY 06', title: 'Tooling Engineered for the Requirement.', text: 'Customized tooling, specialized cutters, die inserts, and precision tooling components manufactured around the application and customer requirement.', image: imageFor('tooling'), alt: 'Custom precision tooling components', set: 'tooling', reverse: false },
  { id: 'jigs-fixtures', label: 'CAPABILITY 07', title: 'Jigs & Fixtures Designed for Accuracy and Repeatability.', text: 'Engineering fixtures for holding, positioning, inspection, welding, and machining support—designed to bring consistency to repeat production without unnecessary complexity.', image: imageFor('jigs-fixtures'), alt: 'Precision jigs and fixtures for component positioning', set: 'fixtures', reverse: true },
];
const Split: React.FC<{ item: typeof sections[number] }> = ({ item }) => (
  <section className="cap-split-section section" id={item.id}><Container><div className={'cap-split-grid cap-page-reveal ' + (item.reverse ? 'cap-split-reverse' : '')}><div className="cap-split-image"><img src={item.image} alt={item.alt} loading="lazy" /></div><div className="cap-split-copy"><span className="eyebrow">{item.label}</span><h2>{item.title}</h2><p>{item.text}</p><div className="cap-chip-list">{features[item.set].map((feature) => <span key={feature}>{feature}</span>)}</div>{(item.id === 'cnc-turning' || item.id === 'vmc-milling') && <Link className="cap-text-link" to="/contact">Discuss Requirement <ArrowRight size={16} /></Link>}</div></div></Container></section>
);

export const CapabilitiesPage: React.FC = () => {
  useEffect(() => {
    const items = document.querySelectorAll<HTMLElement>('.cap-page-reveal');
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: 0.12 });
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, []);
  return <div className="capabilities-page">
    <MetaTags title="Manufacturing Capabilities | CNC, VMC & Precision Machining | Maruti Engineering" description="Explore Maruti Engineering’s CNC turning, VMC milling, precision machining, fabrication, laser cutting, tooling, jigs, fixtures and custom engineering capabilities in Vadodara, Gujarat." keywords="precision engineering company in Vadodara, CNC machining services Vadodara, VMC machining services, drawing-based manufacturing" />
    <section className="cap-page-hero blueprint-pattern"><div className="cap-hero-image"><img src={heroImage} alt="Premium CNC and VMC production environment with machined metallic components" /><div className="cap-hero-overlay" /></div><Container className="cap-hero-inner"><div className="cap-hero-copy cap-page-reveal"><div className="cap-breadcrumb"><Link to="/">Home</Link><ChevronRight size={14} /><span>Capabilities</span></div><span className="eyebrow">MANUFACTURING CAPABILITIES</span><h1>Precision Manufacturing<br /><span className="text-orange">Built Around Your Drawing.</span></h1><p>Maruti Engineering is a precision engineering and contract manufacturing company delivering machined components, tooling, fixtures, fabrication and customized engineering parts according to customer drawings and specifications.</p><div className="cap-hero-actions"><Link className="btn btn-primary btn-lg" to="/contact">Send Your Drawing <ArrowRight size={18} /></Link><Link className="btn btn-outline-white btn-lg" to="/contact">Request a Quote</Link></div></div></Container></section>
    <section className="cap-overview section"><Container><div className="cap-overview-grid cap-page-reveal"><div><span className="eyebrow">WHAT WE DO</span><h2>Integrated Precision Engineering<br /><span className="text-orange">Under One Manufacturing Partner.</span></h2><p className="cap-lead">A precision engineering company in Vadodara built around customer drawings, practical manufacturing support, and long-term industrial partnerships.</p></div><div><p>From CNC machining services and VMC milling to fabrication, tooling, jigs, fixtures and custom machined components, our workflow brings multiple requirements together with a consistent quality focus.</p><div className="cap-highlights">{['Customer Drawing-Based Production', 'Multi-Material Manufacturing', 'Precision Inspection Support', 'Custom Engineering Solutions'].map((item) => <div key={item}><Check size={17} />{item}</div>)}</div></div></div></Container></section>
    <Split item={sections[0]} /><Split item={sections[1]} />
    <section className="cap-dark-feature section section-dark blueprint-pattern" id="precision-machining"><Container><div className="cap-dark-grid cap-page-reveal"><div><span className="eyebrow">CAPABILITY 03</span><h2>Machining Focused on<br /><span className="text-orange">Dimensional Accuracy.</span></h2><p>Every component is machined according to the customer drawing, then supported by measurement, inspection, and conformity checks through multi-stage production.</p><div className="cap-dark-points"><div><ClipboardCheck />Drawing-led process planning</div><div><Ruler />Measurement at critical stages</div><div><ShieldCheck />Conformity to specification</div></div></div><div className="cap-feature-image"><img src={inspectionImage} alt="Dimensional inspection of a machined metal component" loading="lazy" /></div></div></Container></section>
    {sections.slice(2).map((item) => <Split item={item} key={item.id} />)}
    <section className="cap-custom-section section section-soft" id="customized-components"><Container><div className="cap-custom-grid cap-page-reveal"><div><span className="eyebrow">CAPABILITY 08</span><h2>Your Drawing.<br /><span className="text-orange">Our Manufacturing Capability.</span></h2><p>Customized engineering components are developed and manufactured according to customer drawings and specifications, from first review through finished component.</p><Link className="btn btn-primary btn-lg" to="/contact">Upload Your Requirement <ArrowRight size={18} /></Link></div><div className="cap-workflow">{['Drawing', 'Engineering Review', 'Material Selection', 'Manufacturing', 'Inspection', 'Finished Component'].map((step, index) => <div className="cap-workflow-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < 5 && <ArrowRight className="cap-workflow-arrow" size={18} />}</div>)}</div></div></Container></section>
    <section className="cap-materials section section-deep-dark blueprint-pattern"><Container><div className="cap-centered-heading cap-page-reveal"><span className="eyebrow">MATERIAL EXPERIENCE</span><h2>Experience Across <span className="text-orange">Engineering Materials.</span></h2><p>Material selection and final manufacturing approach depend on drawing, design and application requirements.</p></div><div className="cap-material-grid">{['Stainless Steel', 'Alloy Steel', 'Aluminium', 'Brass', 'Copper', 'Hardox'].map((material, index) => <div className="cap-material-card" key={material}><span>0{index + 1}</span><strong>{material}</strong></div>)}</div></Container></section>
    <section className="cap-why section section-dark"><Container><div className="cap-centered-heading cap-page-reveal"><span className="eyebrow">WHY MARUTI ENGINEERING</span><h2>Manufacturing Support<br /><span className="text-orange">Built for Partnership.</span></h2></div><div className="cap-why-grid">{['Experience Since 1996', 'Customized Manufacturing', 'Multi-Industry Experience', 'Diverse Material Experience', 'Integrated Manufacturing Support', 'Quality Focus', 'Customer-Oriented Approach'].map((item) => <div className="cap-why-item" key={item}><Check size={18} />{item}</div>)}</div></Container></section>
    <section className="cap-final-cta section"><div className="cap-final-bg"><img src={heroImage} alt="CNC machining environment prepared for a customer drawing" /><div /></div><Container><div className="cap-final-copy cap-page-reveal"><span className="eyebrow">START A PROJECT</span><h2>Have a Drawing<br /><span className="text-orange">Ready for Manufacturing?</span></h2><p>Share component drawings, material requirements and quantity with our engineering team in Vadodara.</p><div className="cap-hero-actions"><Link className="btn btn-primary btn-lg" to="/contact">Send Your Drawing <ArrowRight size={18} /></Link><Link className="btn btn-outline-white btn-lg" to="/contact">Request a Quote</Link></div></div></Container></section>
  </div>;
};
export default CapabilitiesPage;
