import React, { useEffect } from 'react';
import { ArrowRight, Check, ChevronRight, ClipboardCheck, Cog, Gauge, Layers3, Ruler, ShieldCheck, Sparkles, Users, Wrench } from 'lucide-react';
import { Link } from 'react-router-dom';
import { MetaTags } from '../components/ui/MetaTags';
import { Container } from '../components/layout/Container';
import './QualityPage.css';
import heroImage from '../assets/quality/quality-hero.png';
import inspectionImage from '../assets/quality/quality-inspection.png';
import drawingImage from '../assets/quality/quality-drawing-component.png';
import processImage from '../assets/quality/quality-process.png';
import materialsImage from '../assets/quality/quality-materials.png';
import ctaImage from '../assets/quality/quality-cta.png';

const principles = [
  ['Customer Satisfaction', 'Quality products and timely delivery.', <ShieldCheck key="a" />],
  ['Quality in Every Stage', 'Build quality into every aspect of work.', <Check key="b" />],
  ['Appropriate Technology', 'Use appropriate technology in manufacturing operations.', <Cog key="c" />],
  ['Continuous Improvement', 'Focus on systematic improvement.', <Sparkles key="d" />],
  ['Employee Skills', 'Develop skill and competence.', <Users key="e" />],
  ['Teamwork', 'Work together toward organizational objectives.', <Layers3 key="f" />],
];
const flow = ['Customer Drawing', 'Engineering Review', 'Material Selection', 'Manufacturing', 'In-Process Verification', 'Final Inspection', 'Delivery'];
const capabilities = ['CNC Turning', 'VMC Milling', 'Precision Machining', 'Fabrication', 'Tooling', 'Jigs & Fixtures'];

export const QualityPage: React.FC = () => {
  useEffect(() => {
    const items = document.querySelectorAll<HTMLElement>('.quality-reveal');
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: .12 });
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, []);
  return <div className="quality-page">
    <MetaTags title="Quality & Inspection | Precision Manufacturing | Maruti Engineering" description="Learn about Maruti Engineering’s quality-focused manufacturing approach, dimensional verification, inspection support, continuous improvement and commitment to reliable precision engineering." keywords="precision machining quality control, engineering quality inspection Vadodara, dimensional inspection precision components, quality-focused manufacturing Gujarat" />
    <section className="quality-page-hero blueprint-pattern"><div className="quality-hero-image"><img src={heroImage} alt="Close-up inspection of a precision machined component" /><div /></div><Container><div className="quality-hero-copy quality-reveal"><div className="quality-breadcrumb"><Link to="/">Home</Link><ChevronRight size={14} /><span>Quality</span></div><span className="eyebrow">QUALITY AT MARUTI ENGINEERING</span><h1>Quality<br /><span className="text-orange">Is Built In.</span></h1><p>Quality, consistency and dimensional verification are integrated into Maruti Engineering’s manufacturing approach from drawing review through finished component delivery.</p><Link className="btn btn-primary btn-lg" to="/contact">Discuss Your Quality Requirement <ArrowRight size={18} /></Link></div></Container></section>
    <section className="quality-philosophy section"><Container><div className="quality-philosophy-grid quality-reveal"><div><span className="eyebrow">OUR QUALITY COMMITMENT</span><h2>Precision Starts<br /><span className="text-orange">with Consistency.</span></h2><p>Skill and consistency guide our quality mission. We build quality into each aspect of work while keeping customer satisfaction, timely delivery, appropriate technology, and continuous improvement in view.</p></div><blockquote>“Skill and consistency are the basic guidelines of our quality mission.”</blockquote></div></Container></section>
    <section className="quality-principles section section-soft"><Container><div className="quality-centered quality-reveal"><span className="eyebrow">QUALITY PRINCIPLES</span><h2>Six Commitments.<br /><span className="text-orange">One Consistent Standard.</span></h2></div><div className="quality-principle-grid">{principles.map(([title, text, icon], index) => <div className="quality-principle-card" key={index}><span className="quality-principle-number">0{index + 1}</span><div className="quality-principle-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>)}</div></Container></section>
    <section className="quality-inspection section section-dark blueprint-pattern"><Container><div className="quality-inspection-grid quality-reveal"><div><span className="eyebrow">INSPECTION & DIMENSIONAL VERIFICATION</span><h2>Dimensional Verification<br /><span className="text-orange">Supporting Precision.</span></h2><p>Dedicated measurement and inspection facilities support dimensional checking against drawings and customer requirements. Verification and consistency remain part of the manufacturing workflow, not an afterthought.</p><div className="quality-inspection-points"><div><Ruler /> Measurement and inspection support</div><div><ClipboardCheck /> Verification against drawing</div><div><Gauge /> Customer requirement focus</div></div></div><div className="quality-inspection-image"><img src={inspectionImage} alt="Dimensional verification of a machined component" loading="lazy" /></div></div></Container></section>
    <section className="quality-process section"><Container><div className="quality-centered quality-reveal"><span className="eyebrow">QUALITY THROUGH THE PROCESS</span><h2>Quality Moves with<br /><span className="text-orange">Every Manufacturing Stage.</span></h2></div><div className="quality-process-grid">{flow.map((item, index) => <div className="quality-process-item" key={item}><div className="quality-process-icon">{[<ClipboardCheck key="a" />, <Cog key="b" />, <Layers3 key="c" />, <WrenchIcon key="d" />, <Ruler key="e" />, <ShieldCheck key="f" />, <ArrowRight key="g" />][index]}</div><strong>{item}</strong>{index < flow.length - 1 && <ArrowRight className="quality-process-arrow" size={18} />}</div>)}</div><img className="quality-process-image quality-reveal" src={processImage} alt="Quality process from machining through inspection" loading="lazy" /></Container></section>
    <section className="quality-drawing section section-soft"><Container><div className="quality-drawing-grid quality-reveal"><div><img src={drawingImage} alt="Customer engineering drawing beside a finished machined component" loading="lazy" /></div><div><span className="eyebrow">DRAWING-BASED QUALITY</span><h2>Manufactured Against<br /><span className="text-orange">Customer Requirements.</span></h2><p>Dimensional and manufacturing requirements are derived from supplied drawings and specifications. This gives engineering review, material selection, manufacturing, and final inspection a clear reference point.</p><Link className="quality-inline-link" to="/contact">Share Your Drawing <ArrowRight size={16} /></Link></div></div></Container></section>
    <section className="quality-materials section section-deep-dark blueprint-pattern"><Container><div className="quality-material-grid quality-reveal"><div><span className="eyebrow">MATERIAL & PROCESS AWARENESS</span><h2>Material Context<br /><span className="text-orange">Matters to Quality.</span></h2><p>Manufacturing and inspection approaches may vary according to material and design requirements. Final material selection remains dependent on the drawing and application.</p></div><div className="quality-material-list">{['Stainless Steel', 'Alloy Steel', 'Aluminium', 'Brass', 'Copper', 'Hardox'].map((item) => <span key={item}>{item}</span>)}</div></div><img className="quality-material-image quality-reveal" src={materialsImage} alt="Engineering materials arranged for quality review" loading="lazy" /></Container></section>
    <section className="quality-improvement section section-soft"><Container><div className="quality-improvement-grid quality-reveal"><div><span className="eyebrow">CONTINUOUS IMPROVEMENT</span><h2>Improving Process.<br /><span className="text-orange">Strengthening Reliability.</span></h2></div><div><p>Appropriate technology, employee skill development, consistent work practices, continuous improvement, and team-based execution help strengthen reliability across the manufacturing workflow.</p><div className="quality-improvement-tags">{['Appropriate technology', 'Employee development', 'Consistent work', 'Team execution'].map((item) => <span key={item}><Check size={15} />{item}</span>)}</div></div></div></Container></section>
    <section className="quality-capabilities section"><Container><div className="quality-centered quality-reveal"><span className="eyebrow">QUALITY + CAPABILITIES</span><h2>Quality Supporting<br /><span className="text-orange">Every Manufacturing Capability.</span></h2></div><div className="quality-capability-grid">{capabilities.map((item, index) => <Link className="quality-capability-card" to="/capabilities.html" key={item}><span>0{index + 1}</span><strong>{item}</strong><ArrowRight size={18} /></Link>)}</div></Container></section>
    <section className="quality-customer-cta section"><div className="quality-cta-bg"><img src={ctaImage} alt="Quality-focused precision components in a manufacturing environment" /><div /></div><Container><div className="quality-customer-copy quality-reveal"><span className="eyebrow">CUSTOMER-FOCUSED QUALITY</span><h2>Quality Focused.<br /><span className="text-orange">Customer Oriented.</span></h2><p>We focus on understanding the correct manufacturing requirement, communicating reliably, delivering quality, and building long-term relationships.</p><Link className="btn btn-primary btn-lg" to="/contact">Discuss Your Requirement <ArrowRight size={18} /></Link></div></Container></section>
    <section className="quality-final section section-dark"><Container><div className="quality-final-copy quality-reveal"><span className="eyebrow">START A PROJECT</span><h2>Need a Component<br /><span className="text-orange">Manufactured to Your Drawing?</span></h2><p>Share your drawing, material, quantity, and inspection requirements with our engineering team.</p><div className="quality-final-actions"><Link className="btn btn-primary btn-lg" to="/contact">Send Your Drawing <ArrowRight size={18} /></Link><Link className="btn btn-outline-white btn-lg" to="/contact">Request a Quote</Link></div></div></Container></section>
  </div>;
};
const WrenchIcon: React.FC = () => <Wrench />;
export default QualityPage;
